version: '3.0'

services:
  api:
    build: .
    restart: on-failure
    networks:
      - service-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
    volumes:
      - ./src:/app/src
  postgres:
    build: ./db/
    restart: on-failure
    networks:
      - service-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
  db-logs:

networks:
  service-network:
